# Generated by Django 5.2.17 on 2026-09-28 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_debt_reminders"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("payme", "Payme"), ("click", "Click")], max_length=10
                    ),
                ),
                ("months", models.PositiveSmallIntegerField(default=1)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Summa (so'm)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("pending", "Jarayonda"),
                            ("paid", "To'langan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "provider_trans_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("payme_state", models.SmallIntegerField(default=0)),
                ("payme_create_time", models.BigIntegerField(default=0)),
                ("payme_perform_time", models.BigIntegerField(default=0)),
                ("payme_cancel_time", models.BigIntegerField(default=0)),
                ("cancel_reason", models.SmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_payments",
                        to="core.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Obuna to'lovi",
                "verbose_name_plural": "Obuna to'lovlari",
                "ordering": ["-created_at"],
            },
        ),
    ]
