# Generated by Django 5.2.17 on 2026-10-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Bepul"),
                    ("standard", "Standart"),
                    ("business", "Biznes"),
                ],
                default="standard",
                max_length=20,
                verbose_name="Tarif",
            ),
        ),
    ]
