# Generated by Django 6.0 on 2025-12-18 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='F.I.SH')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('invite_token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Do'kon nomi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bot Token')),
                ('is_active', models.BooleanField(default=True, verbose_name="To'lov qilinganmi?")),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Egasining logini')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.DecimalField(decimal_places=2, default=12800, max_digits=10, verbose_name='Dollar kursi')),
                ('shop', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Naqd'), ('card', 'Plastik (Humo/Uzcard)'), ('click', 'Click / Payme'), ('transfer', 'Perechislenie')], max_length=20, null=True, verbose_name="To'lov turi")),
                ('transaction_type', models.CharField(choices=[('debt', 'Nasiya (Qarz)'), ('payment', "To'lov (Qaytarish)")], default='debt', max_length=10)),
                ('amount_uzs', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name="So'm qismi")),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dollar qismi')),
                ('items', models.TextField(verbose_name="Tovarlar ro'yxati")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.shop')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.shop'),
        ),
        migrations.CreateModel(
            name='AllowedAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Xodim Ismi')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('worker', 'Xodim')], default='admin', max_length=20)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop', verbose_name="Do'kon")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('shop', 'phone')},
        ),
    ]
