# Generated by Django 5.2.17 on 2026-09-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="is_cash_sale",
            field=models.BooleanField(default=False, verbose_name="Naqd savdo"),
        ),
        migrations.AlterField(
            model_name="debt",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Naqd"),
                    ("card", "Plastik (Humo/Uzcard)"),
                    ("click", "Click / Payme"),
                    ("transfer", "O'tkazma (Perechislenie)"),
                ],
                max_length=20,
                null=True,
                verbose_name="To'lov turi",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("shop", "phone")},
        ),
    ]
