# Generated by Django 5.2.17 on 2026-09-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_staff_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_reminded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Oxirgi eslatma"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="reminder_days",
            field=models.PositiveSmallIntegerField(
                default=7, verbose_name="Necha kunda bir"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="reminder_enabled",
            field=models.BooleanField(default=False, verbose_name="Avtomatik eslatma"),
        ),
        migrations.AddField(
            model_name="settings",
            name="reminder_min_debt",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=15,
                verbose_name="Eng kam qarz (so'm)",
            ),
        ),
    ]
