# Generated by Django 5.2.17 on 2026-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_debt_reminders"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="reject_reason",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Rad etish sababi"
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="shop_note",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Do'kon izohi"
            ),
        ),
    ]
