# Generated by Django 5.2.17 on 2026-10-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_debt_reject_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("name", "Do'kon nomi kutilmoqda"),
                            ("category", "Do'kon turi kutilmoqda"),
                        ],
                        default="name",
                        max_length=20,
                    ),
                ),
                ("shop_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="shop",
            name="category",
            field=models.CharField(
                choices=[
                    ("grocery", "Oziq-ovqat"),
                    ("construction", "Qurilish mollari"),
                    ("plumbing", "Santexnika"),
                    ("tech", "Maishiy texnika"),
                    ("electronics", "Telefon va elektronika"),
                    ("clothing", "Kiyim-kechak"),
                    ("household", "Xo'jalik mollari"),
                    ("auto", "Avto ehtiyot qismlar"),
                    ("pharmacy", "Dorixona"),
                    ("cosmetics", "Kosmetika va parfyumeriya"),
                    ("furniture", "Mebel"),
                    ("other", "Boshqa"),
                ],
                default="other",
                max_length=20,
                verbose_name="Do'kon turi",
            ),
        ),
    ]
