# Generated by Django 5.2.17 on 2026-10-03 15:22

from django.db import migrations, models


def existing_shops_to_standard(apps, schema_editor):
    # Tariflardan oldingi do'konlar bitta pullik tarifda edi: obuna muddati o'zgarmaydi,
    # muddati yo'q (cheksiz) do'konlar ham avvalgidek cheksiz qoladi.
    apps.get_model('core', 'Shop').objects.update(plan='standard')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_bot_signup"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="launch_price_locked",
            field=models.BooleanField(
                default=False, verbose_name="Ishga tushirish narxi saqlangan"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Bepul"),
                    ("standard", "Standart"),
                    ("business", "Biznes"),
                ],
                default="free",
                max_length=20,
                verbose_name="Tarif",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="subscription_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Bo'sh - muddatsiz",
                null=True,
                verbose_name="Tarif tugash vaqti",
            ),
        ),
        migrations.RunPython(existing_shops_to_standard, migrations.RunPython.noop),
    ]
