# Generated by Django 5.2.17 on 2026-10-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_shop_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="To'lov muddati"
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="due_stage",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
