# Generated by Django 5.2.17 on 2026-10-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_debt_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="is_opening",
            field=models.BooleanField(
                default=False, verbose_name="Daftardan ko'chirilgan"
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="opening_ack",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
