# Generated by Django 5.2.17 on 2026-10-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_opening_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="risk_flag",
            field=models.BooleanField(default=False, verbose_name="Ehtiyot bo'ling"),
        ),
        migrations.AddField(
            model_name="client",
            name="risk_note",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Yopiq izoh"
            ),
        ),
    ]
